server.port=9001

# H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

# External configuration
mes-configs.limitDeProduits=5

# Actuator
management.endpoints.web.exposure.include=*
