server.port=9001

spring.cloud.config.allowOverride=true
spring.cloud.config.overrideNone=true
spring.cloud.config.overrideSystemProperties=false

spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=*

mes-configs.limitDeProduits=2
eureka.client.serviceUrl.defaultZone=http://localhost:9102/eureka/

# Do not recreate/rebind Eureka client during /actuator/refresh
eureka.client.refresh.enable=false
